# Generated by Django 3.2 on 2021-06-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('tilte', models.CharField(max_length=100)),
                ('head0', models.CharField(default='', max_length=200)),
                ('head1', models.CharField(default='', max_length=200)),
                ('head2', models.CharField(default='', max_length=200)),
                ('pub_date', models.DateField()),
                ('thumbnail', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
