# Generated by Django 3.2 on 2021-06-03 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_orderupadate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderUpadate',
            new_name='OrderUpdate',
        ),
    ]
